'use client';
import './globals.css';
import { inter } from './fonts';
import { michroma } from './fonts';
import { Providers } from './providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={`${inter.variable} ${michroma.variable}`}>
      <body>
        <Providers> {children}</Providers>
      </body>
    </html>
  );
}
